name: sse_processor
description: A pure Dart package for Server-Sent Events (SSE) delivery management

version: 1.0.0+4

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.0.0"

homepage: https://github.com/Nero9891/sse_processor
repository: https://github.com/Nero9891/sse_processor
issue_tracker: https://github.com/Nero9891/sse_processor/issues

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  built_collection: ^5.1.1
  synchronized: ^3.1.0
  dio: ^5.4.3+1
  get: ^4.6.6